version: '3.1'

services:
  db:
    network_mode: default
    image: mysql:5.7
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Mysql12345
    # volumes: 
    #   - ./data:/var/lib/mysql
    ports:
      - 3306:3306

